### ISSUE TITLE
using shell module is a bad idea

### ISSUE THREAD

**Issue by l00ptr** [Worteks/ansible-lemonldapng#1]
Using (or almost) exclusively the shell ansible module is a bad idea. We can replace some of them to respect the ansible best practices.

By example instead of using shell module to import a GPG key for debian/apt we can use the apt_key module:
```
- name: Install LLNG Repository KEY
  copy: src=rpm-gpg-key-ow2 dest=/tmp/gpg-key-ow2 owner=root group=root mode=0644
- name: Check for Missing Trusted Key
  changed_when: "has_apt_key.rc != 0"
  failed_when: false
  register: has_apt_key
  shell: apt-key list | sed 's| ||g' | grep -i {{ lemonldap_gpg_pubkey_id }}
- name: Import LLNG GPG KEY
  shell: apt-key add gpg-key-ow2 chdir=/tmp
when: has_apt_key is defined and has_apt_key.rc is defined and has_apt_key.rc != 0
```

Can become:
```
- name: Install LLNG Repository KEY
  copy: 
    src: rpm-gpg-key-ow2 
    dest: /tmp/gpg-key-ow2 
    owner: root 
    group: root 
    mode: 0644

- name: Import LLNG GPG KEY
  apt_key:
    file: /tmp/gpg-key-ow2
    state: present
```
It's easier to read and more in the ansible spirit :)
